language: go
go:
  - 1.9.x
script:
  - make build-all
deploy:
  provider: releases
  api_key:
    secure: KsIvM9L6otnjdJ0CszQ0LVxr6ZRElkRMiHhguYeDv+/4Lu4ecV85DGqiFswVOkQ4d4ilsN+CtCu/zxx4+/pG9Ya5aGe+eWanxYhw6cVB2vhsSu3nAygdl7vPilbd3HyaGkJGY5PV6nqIceCIElAwcfL0vhXEGAtJdRVjmsYIpQFLGIdiT36zwLu24XAZupPXboDZ+ORURLSoAjS3aCBLXGsDyyIRUEG8UvuFfJ38u9iqzdX+5enKUaTooXCzRyEe2hirlScHl642hN5pOB+wVk7UzP4wuuesgsWhcPwJVkpsfvVQ+kr4Pcp78L7Jgv20rWWPmXhWpodzpoThBYUl1RJpyJQK72fkpHQujz1DW16Uqx2sped2B7kzheuqvtUbke/q6ToMHjnZqvzPyB/jqQxFP/vjK6mwz++ryPEnldMt6NLmyoUba461REpLBZFPgJoXBTvfsodHxeBeMOyMO4Rjw/DVtd+AOpduBTbzUi6t4Fxu30AwL1vwOv4gkGvF68tQ1tu8EGsTUS6fc33oEL0BmSYJ94BjtAu39LkJm/tkwblcCe+hVs/ntOsENJ5VwDrEg5DCwG/jrJn5kX3UQQ2GJEyddpm3CAPydURZg9kAG1zmfpNJCWgLc3IYJUzmgtFb1cbXFGdApfFymlka4eayhenHQpchsPvpp2XdG/o=
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    repo: graylog-labs/udpcat
